#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    # Stop and disable service
    systemctl stop unbound-webui.service || true
    systemctl disable unbound-webui.service || true
fi

# Automatically added by dh_systemd_start/13.11.4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'unbound-webui.service' >/dev/null || true
fi
# End automatically added section

